KANJI_SEED = [
    # numbers
    {"character": "一", "meaning_en": "one", "onyomi": "イチ", "kunyomi": "ひと", "compound_word": "一つ", "compound_reading": "ひとつ", "compound_meaning_en": "one thing", "category": "numbers"},
    {"character": "二", "meaning_en": "two", "onyomi": "ニ", "kunyomi": "ふた", "compound_word": "二人", "compound_reading": "ふたり", "compound_meaning_en": "two people", "category": "numbers"},
    {"character": "三", "meaning_en": "three", "onyomi": "サン", "kunyomi": "み", "compound_word": "三日", "compound_reading": "みっか", "compound_meaning_en": "3rd day / 3 days", "category": "numbers"},
    {"character": "四", "meaning_en": "four", "onyomi": "シ", "kunyomi": "よん, よ", "compound_word": "四月", "compound_reading": "しがつ", "compound_meaning_en": "April", "category": "numbers"},
    {"character": "五", "meaning_en": "five", "onyomi": "ゴ", "kunyomi": "いつ", "compound_word": "五分", "compound_reading": "ごふん", "compound_meaning_en": "5 minutes", "category": "numbers"},
    {"character": "六", "meaning_en": "six", "onyomi": "ロク", "kunyomi": "む", "compound_word": "六時", "compound_reading": "ろくじ", "compound_meaning_en": "6 o'clock", "category": "numbers"},
    {"character": "七", "meaning_en": "seven", "onyomi": "シチ", "kunyomi": "なな", "compound_word": "七月", "compound_reading": "しちがつ", "compound_meaning_en": "July", "category": "numbers"},
    {"character": "八", "meaning_en": "eight", "onyomi": "ハチ", "kunyomi": "や", "compound_word": "八日", "compound_reading": "ようか", "compound_meaning_en": "8th day", "category": "numbers"},
    {"character": "九", "meaning_en": "nine", "onyomi": "キュウ", "kunyomi": "ここの", "compound_word": "九時", "compound_reading": "くじ", "compound_meaning_en": "9 o'clock", "category": "numbers"},
    {"character": "十", "meaning_en": "ten", "onyomi": "ジュウ", "kunyomi": "とお", "compound_word": "十分", "compound_reading": "じゅっぷん", "compound_meaning_en": "10 minutes", "category": "numbers"},
    {"character": "百", "meaning_en": "hundred", "onyomi": "ヒャク", "kunyomi": None, "compound_word": "百円", "compound_reading": "ひゃくえん", "compound_meaning_en": "100 yen", "category": "numbers"},
    {"character": "千", "meaning_en": "thousand", "onyomi": "セン", "kunyomi": None, "compound_word": "千円", "compound_reading": "せんえん", "compound_meaning_en": "1000 yen", "category": "numbers"},
    {"character": "万", "meaning_en": "ten thousand", "onyomi": "マン", "kunyomi": None, "compound_word": "一万円", "compound_reading": "いちまんえん", "compound_meaning_en": "10,000 yen", "category": "numbers"},
    {"character": "円", "meaning_en": "yen / circle", "onyomi": "エン", "kunyomi": None, "compound_word": "百円", "compound_reading": "ひゃくえん", "compound_meaning_en": "100 yen", "category": "numbers"},

    # time
    {"character": "日", "meaning_en": "day / sun", "onyomi": "ニチ", "kunyomi": "ひ, か", "compound_word": "日曜日", "compound_reading": "にちようび", "compound_meaning_en": "Sunday", "category": "time"},
    {"character": "月", "meaning_en": "month / moon", "onyomi": "ゲツ", "kunyomi": "つき", "compound_word": "月曜日", "compound_reading": "げつようび", "compound_meaning_en": "Monday", "category": "time"},
    {"character": "火", "meaning_en": "fire", "onyomi": "カ", "kunyomi": "ひ", "compound_word": "火曜日", "compound_reading": "かようび", "compound_meaning_en": "Tuesday", "category": "time"},
    {"character": "水", "meaning_en": "water", "onyomi": "スイ", "kunyomi": "みず", "compound_word": "水曜日", "compound_reading": "すいようび", "compound_meaning_en": "Wednesday", "category": "time"},
    {"character": "木", "meaning_en": "tree / wood", "onyomi": "モク", "kunyomi": "き", "compound_word": "木曜日", "compound_reading": "もくようび", "compound_meaning_en": "Thursday", "category": "time"},
    {"character": "金", "meaning_en": "gold / money", "onyomi": "キン", "kunyomi": "かね", "compound_word": "金曜日", "compound_reading": "きんようび", "compound_meaning_en": "Friday", "category": "time"},
    {"character": "土", "meaning_en": "earth / soil", "onyomi": "ド", "kunyomi": "つち", "compound_word": "土曜日", "compound_reading": "どようび", "compound_meaning_en": "Saturday", "category": "time"},
    {"character": "年", "meaning_en": "year", "onyomi": "ネン", "kunyomi": "とし", "compound_word": "今年", "compound_reading": "ことし", "compound_meaning_en": "this year", "category": "time"},
    {"character": "時", "meaning_en": "time / hour", "onyomi": "ジ", "kunyomi": "とき", "compound_word": "時間", "compound_reading": "じかん", "compound_meaning_en": "time", "category": "time"},
    {"character": "分", "meaning_en": "minute / part; to understand / divide", "onyomi": "フン、ブン", "kunyomi": "わ(ける)、わ(かる)", "compound_word": "三分 / 分かる", "compound_reading": "さんぷん / わかる", "compound_meaning_en": "3 minutes / to understand", "category": "time"},
    {"character": "半", "meaning_en": "half", "onyomi": "ハン", "kunyomi": None, "compound_word": "半分", "compound_reading": "はんぶん", "compound_meaning_en": "half", "category": "time"},
    {"character": "今", "meaning_en": "now", "onyomi": "コン", "kunyomi": "いま", "compound_word": "今日", "compound_reading": "きょう", "compound_meaning_en": "today", "category": "time"},
    {"character": "週", "meaning_en": "week", "onyomi": "シュウ", "kunyomi": None, "compound_word": "今週", "compound_reading": "こんしゅう", "compound_meaning_en": "this week", "category": "time"},
    {"character": "毎", "meaning_en": "every", "onyomi": "マイ", "kunyomi": None, "compound_word": "毎日", "compound_reading": "まいにち", "compound_meaning_en": "every day", "category": "time"},
    {"character": "前", "meaning_en": "before / front", "onyomi": "ゼン", "kunyomi": "まえ", "compound_word": "午前", "compound_reading": "ごぜん", "compound_meaning_en": "a.m.", "category": "time"},
    {"character": "後", "meaning_en": "after / behind", "onyomi": "ゴ", "kunyomi": "あと, うし(ろ)", "compound_word": "午後", "compound_reading": "ごご", "compound_meaning_en": "p.m.", "category": "time"},

    # people_family
    {"character": "人", "meaning_en": "person", "onyomi": "ジン", "kunyomi": "ひと", "compound_word": "日本人", "compound_reading": "にほんじん", "compound_meaning_en": "Japanese person", "category": "people_family"},
    {"character": "私", "meaning_en": "I / private", "onyomi": "シ", "kunyomi": "わたし", "compound_word": "私", "compound_reading": "わたし", "compound_meaning_en": "I", "category": "people_family"},
    {"character": "名", "meaning_en": "name", "onyomi": "メイ", "kunyomi": "な", "compound_word": "名前", "compound_reading": "なまえ", "compound_meaning_en": "name", "category": "people_family"},
    {"character": "男", "meaning_en": "man", "onyomi": "ダン", "kunyomi": "おとこ", "compound_word": "男の人", "compound_reading": "おとこのひと", "compound_meaning_en": "man", "category": "people_family"},
    {"character": "女", "meaning_en": "woman", "onyomi": "ジョ", "kunyomi": "おんな", "compound_word": "女の人", "compound_reading": "おんなのひと", "compound_meaning_en": "woman", "category": "people_family"},
    {"character": "子", "meaning_en": "child", "onyomi": "シ", "kunyomi": "こ", "compound_word": "子供", "compound_reading": "こども", "compound_meaning_en": "child", "category": "people_family"},
    {"character": "父", "meaning_en": "father", "onyomi": "フ", "kunyomi": "ちち", "compound_word": "父", "compound_reading": "ちち", "compound_meaning_en": "my father", "category": "people_family"},
    {"character": "母", "meaning_en": "mother", "onyomi": "ボ", "kunyomi": "はは", "compound_word": "母", "compound_reading": "はは", "compound_meaning_en": "my mother", "category": "people_family"},
    {"character": "友", "meaning_en": "friend", "onyomi": "ユウ", "kunyomi": "とも", "compound_word": "友達", "compound_reading": "ともだち", "compound_meaning_en": "friend", "category": "people_family"},
    {"character": "学", "meaning_en": "study / learning", "onyomi": "ガク", "kunyomi": "まな(ぶ)", "compound_word": "学生", "compound_reading": "がくせい", "compound_meaning_en": "student", "category": "people_family"},
    {"character": "生", "meaning_en": "life / birth", "onyomi": "セイ", "kunyomi": "い(きる)", "compound_word": "先生", "compound_reading": "せんせい", "compound_meaning_en": "teacher", "category": "people_family"},

    # places
    {"character": "本", "meaning_en": "book / origin", "onyomi": "ホン", "kunyomi": "もと", "compound_word": "本", "compound_reading": "ほん", "compound_meaning_en": "book", "category": "places"},
    {"character": "国", "meaning_en": "country", "onyomi": "コク", "kunyomi": "くに", "compound_word": "中国", "compound_reading": "ちゅうごく", "compound_meaning_en": "China", "category": "places"},
    {"character": "中", "meaning_en": "middle / inside", "onyomi": "チュウ", "kunyomi": "なか", "compound_word": "中国", "compound_reading": "ちゅうごく", "compound_meaning_en": "China", "category": "places"},
    {"character": "外", "meaning_en": "outside", "onyomi": "ガイ", "kunyomi": "そと", "compound_word": "外国", "compound_reading": "がいこく", "compound_meaning_en": "foreign country", "category": "places"},
    {"character": "上", "meaning_en": "up / above", "onyomi": "ジョウ", "kunyomi": "うえ", "compound_word": "上手", "compound_reading": "じょうず", "compound_meaning_en": "skillful", "category": "places"},
    {"character": "下", "meaning_en": "down / below", "onyomi": "カ", "kunyomi": "した", "compound_word": "下手", "compound_reading": "へた", "compound_meaning_en": "unskillful", "category": "places"},
    {"character": "左", "meaning_en": "left", "onyomi": "サ", "kunyomi": "ひだり", "compound_word": "左", "compound_reading": "ひだり", "compound_meaning_en": "left", "category": "places"},
    {"character": "右", "meaning_en": "right", "onyomi": "ウ", "kunyomi": "みぎ", "compound_word": "右", "compound_reading": "みぎ", "compound_meaning_en": "right", "category": "places"},
    {"character": "東", "meaning_en": "east", "onyomi": "トウ", "kunyomi": "ひがし", "compound_word": "東京", "compound_reading": "とうきょう", "compound_meaning_en": "Tokyo", "category": "places"},
    {"character": "西", "meaning_en": "west", "onyomi": "セイ", "kunyomi": "にし", "compound_word": "西口", "compound_reading": "にしぐち", "compound_meaning_en": "west exit", "category": "places"},
    {"character": "南", "meaning_en": "south", "onyomi": "ナン", "kunyomi": "みなみ", "compound_word": "南口", "compound_reading": "みなみぐち", "compound_meaning_en": "south exit", "category": "places"},
    {"character": "北", "meaning_en": "north", "onyomi": "ホク", "kunyomi": "きた", "compound_word": "北口", "compound_reading": "きたぐち", "compound_meaning_en": "north exit", "category": "places"},
    {"character": "校", "meaning_en": "school", "onyomi": "コウ", "kunyomi": None, "compound_word": "学校", "compound_reading": "がっこう", "compound_meaning_en": "school", "category": "places"},
    {"character": "店", "meaning_en": "store / shop", "onyomi": "テン", "kunyomi": "みせ", "compound_word": "店", "compound_reading": "みせ", "compound_meaning_en": "shop", "category": "places"},
    {"character": "駅", "meaning_en": "station", "onyomi": "エキ", "kunyomi": None, "compound_word": "駅", "compound_reading": "えき", "compound_meaning_en": "station", "category": "places"},
    {"character": "道", "meaning_en": "road / way", "onyomi": "ドウ", "kunyomi": "みち", "compound_word": "道", "compound_reading": "みち", "compound_meaning_en": "road", "category": "places"},
    {"character": "家", "meaning_en": "house / home", "onyomi": "カ", "kunyomi": "いえ, うち", "compound_word": "家", "compound_reading": "いえ", "compound_meaning_en": "house", "category": "places"},

    # nature
    {"character": "山", "meaning_en": "mountain", "onyomi": "サン", "kunyomi": "やま", "compound_word": "山", "compound_reading": "やま", "compound_meaning_en": "mountain", "category": "nature"},
    {"character": "川", "meaning_en": "river", "onyomi": "セン", "kunyomi": "かわ", "compound_word": "川", "compound_reading": "かわ", "compound_meaning_en": "river", "category": "nature"},
    {"character": "天", "meaning_en": "heaven / sky", "onyomi": "テン", "kunyomi": None, "compound_word": "天気", "compound_reading": "てんき", "compound_meaning_en": "weather", "category": "nature"},
    {"character": "気", "meaning_en": "spirit / air", "onyomi": "キ", "kunyomi": None, "compound_word": "元気", "compound_reading": "げんき", "compound_meaning_en": "energetic", "category": "nature"},
    {"character": "空", "meaning_en": "sky / empty", "onyomi": "クウ", "kunyomi": "そら", "compound_word": "空", "compound_reading": "そら", "compound_meaning_en": "sky", "category": "nature"},
    {"character": "花", "meaning_en": "flower", "onyomi": "カ", "kunyomi": "はな", "compound_word": "花", "compound_reading": "はな", "compound_meaning_en": "flower", "category": "nature"},
    {"character": "雨", "meaning_en": "rain", "onyomi": "ウ", "kunyomi": "あめ", "compound_word": "雨", "compound_reading": "あめ", "compound_meaning_en": "rain", "category": "nature"},

    # body_health
    {"character": "目", "meaning_en": "eye", "onyomi": "モク", "kunyomi": "め", "compound_word": "目", "compound_reading": "め", "compound_meaning_en": "eye", "category": "body_health"},
    {"character": "耳", "meaning_en": "ear", "onyomi": "ジ", "kunyomi": "みみ", "compound_word": "耳", "compound_reading": "みみ", "compound_meaning_en": "ear", "category": "body_health"},
    {"character": "口", "meaning_en": "mouth", "onyomi": "コウ", "kunyomi": "くち", "compound_word": "入口", "compound_reading": "いりぐち", "compound_meaning_en": "entrance", "category": "body_health"},
    {"character": "手", "meaning_en": "hand", "onyomi": "シュ", "kunyomi": "て", "compound_word": "手紙", "compound_reading": "てがみ", "compound_meaning_en": "letter", "category": "body_health"},
    {"character": "足", "meaning_en": "foot / leg", "onyomi": "ソク", "kunyomi": "あし", "compound_word": "足", "compound_reading": "あし", "compound_meaning_en": "foot", "category": "body_health"},
    {"character": "体", "meaning_en": "body", "onyomi": "タイ", "kunyomi": "からだ", "compound_word": "体", "compound_reading": "からだ", "compound_meaning_en": "body", "category": "body_health"},

    # verbs
    {"character": "食", "meaning_en": "eat", "onyomi": "ショク", "kunyomi": "た(べる)", "compound_word": "食べる", "compound_reading": "たべる", "compound_meaning_en": "to eat", "category": "verbs"},
    {"character": "飲", "meaning_en": "drink", "onyomi": "イン", "kunyomi": "の(む)", "compound_word": "飲む", "compound_reading": "のむ", "compound_meaning_en": "to drink", "category": "verbs"},
    {"character": "見", "meaning_en": "see / look", "onyomi": "ケン", "kunyomi": "み(る)", "compound_word": "見る", "compound_reading": "みる", "compound_meaning_en": "to see", "category": "verbs"},
    {"character": "聞", "meaning_en": "hear / ask", "onyomi": "ブン", "kunyomi": "き(く)", "compound_word": "聞く", "compound_reading": "きく", "compound_meaning_en": "to hear / ask", "category": "verbs"},
    {"character": "話", "meaning_en": "speak", "onyomi": "ワ", "kunyomi": "はな(す)", "compound_word": "話す", "compound_reading": "はなす", "compound_meaning_en": "to speak", "category": "verbs"},
    {"character": "読", "meaning_en": "read", "onyomi": "ドク", "kunyomi": "よ(む)", "compound_word": "読む", "compound_reading": "よむ", "compound_meaning_en": "to read", "category": "verbs"},
    {"character": "書", "meaning_en": "write", "onyomi": "ショ", "kunyomi": "か(く)", "compound_word": "書く", "compound_reading": "かく", "compound_meaning_en": "to write", "category": "verbs"},
    {"character": "買", "meaning_en": "buy", "onyomi": "バイ", "kunyomi": "か(う)", "compound_word": "買う", "compound_reading": "かう", "compound_meaning_en": "to buy", "category": "verbs"},
    {"character": "行", "meaning_en": "go", "onyomi": "コウ", "kunyomi": "い(く)", "compound_word": "行く", "compound_reading": "いく", "compound_meaning_en": "to go", "category": "verbs"},
    {"character": "来", "meaning_en": "come", "onyomi": "ライ", "kunyomi": "く(る)", "compound_word": "来る", "compound_reading": "くる", "compound_meaning_en": "to come", "category": "verbs"},
    {"character": "出", "meaning_en": "exit / leave", "onyomi": "シュツ", "kunyomi": "で(る)", "compound_word": "出る", "compound_reading": "でる", "compound_meaning_en": "to go out", "category": "verbs"},
    {"character": "入", "meaning_en": "enter", "onyomi": "ニュウ", "kunyomi": "はい(る)", "compound_word": "入る", "compound_reading": "はいる", "compound_meaning_en": "to enter", "category": "verbs"},
    {"character": "立", "meaning_en": "stand", "onyomi": "リツ", "kunyomi": "た(つ)", "compound_word": "立つ", "compound_reading": "たつ", "compound_meaning_en": "to stand", "category": "verbs"},
    {"character": "休", "meaning_en": "rest", "onyomi": "キュウ", "kunyomi": "やす(む)", "compound_word": "休む", "compound_reading": "やすむ", "compound_meaning_en": "to rest", "category": "verbs"},
    {"character": "会", "meaning_en": "meet", "onyomi": "カイ", "kunyomi": "あ(う)", "compound_word": "会う", "compound_reading": "あう", "compound_meaning_en": "to meet", "category": "verbs"},
    {"character": "帰", "meaning_en": "return home", "onyomi": "キ", "kunyomi": "かえ(る)", "compound_word": "帰る", "compound_reading": "かえる", "compound_meaning_en": "to go home", "category": "verbs"},
    {"character": "作", "meaning_en": "make", "onyomi": "サク", "kunyomi": "つく(る)", "compound_word": "作る", "compound_reading": "つくる", "compound_meaning_en": "to make", "category": "verbs"},
    {"character": "思", "meaning_en": "think", "onyomi": "シ", "kunyomi": "おも(う)", "compound_word": "思う", "compound_reading": "おもう", "compound_meaning_en": "to think", "category": "verbs"},
    {"character": "言", "meaning_en": "say", "onyomi": "ゲン", "kunyomi": "い(う)", "compound_word": "言う", "compound_reading": "いう", "compound_meaning_en": "to say", "category": "verbs"},

    # adjectives
    {"character": "大", "meaning_en": "big", "onyomi": "ダイ", "kunyomi": "おお(きい)", "compound_word": "大きい", "compound_reading": "おおきい", "compound_meaning_en": "big", "category": "adjectives"},
    {"character": "小", "meaning_en": "small", "onyomi": "ショウ", "kunyomi": "ちい(さい)", "compound_word": "小さい", "compound_reading": "ちいさい", "compound_meaning_en": "small", "category": "adjectives"},
    {"character": "高", "meaning_en": "tall / expensive", "onyomi": "コウ", "kunyomi": "たか(い)", "compound_word": "高い", "compound_reading": "たかい", "compound_meaning_en": "expensive", "category": "adjectives"},
    {"character": "安", "meaning_en": "cheap / peaceful", "onyomi": "アン", "kunyomi": "やす(い)", "compound_word": "安い", "compound_reading": "やすい", "compound_meaning_en": "cheap", "category": "adjectives"},
    {"character": "新", "meaning_en": "new", "onyomi": "シン", "kunyomi": "あたら(しい)", "compound_word": "新しい", "compound_reading": "あたらしい", "compound_meaning_en": "new", "category": "adjectives"},
    {"character": "古", "meaning_en": "old", "onyomi": "コ", "kunyomi": "ふる(い)", "compound_word": "古い", "compound_reading": "ふるい", "compound_meaning_en": "old", "category": "adjectives"},
    {"character": "長", "meaning_en": "long", "onyomi": "チョウ", "kunyomi": "なが(い)", "compound_word": "長い", "compound_reading": "ながい", "compound_meaning_en": "long", "category": "adjectives"},
    {"character": "多", "meaning_en": "many", "onyomi": "タ", "kunyomi": "おお(い)", "compound_word": "多い", "compound_reading": "おおい", "compound_meaning_en": "many", "category": "adjectives"},
    {"character": "少", "meaning_en": "few / little", "onyomi": "ショウ", "kunyomi": "すこ(し)", "compound_word": "少し", "compound_reading": "すこし", "compound_meaning_en": "a little", "category": "adjectives"},
    {"character": "白", "meaning_en": "white", "onyomi": "ハク", "kunyomi": "しろ", "compound_word": "白い", "compound_reading": "しろい", "compound_meaning_en": "white", "category": "adjectives"},
    {"character": "黒", "meaning_en": "black", "onyomi": "コク", "kunyomi": "くろ", "compound_word": "黒い", "compound_reading": "くろい", "compound_meaning_en": "black", "category": "adjectives"},

    # misc
    {"character": "何", "meaning_en": "what", "onyomi": "カ", "kunyomi": "なに, なん", "compound_word": "何", "compound_reading": "なに", "compound_meaning_en": "what", "category": "misc"},
    {"character": "度", "meaning_en": "degree / times", "onyomi": "ド", "kunyomi": None, "compound_word": "一度", "compound_reading": "いちど", "compound_meaning_en": "once", "category": "misc"},
    {"character": "番", "meaning_en": "number / order", "onyomi": "バン", "kunyomi": None, "compound_word": "番号", "compound_reading": "ばんごう", "compound_meaning_en": "number", "category": "misc"},
    {"character": "門", "meaning_en": "door / entrance", "onyomi": "モン", "kunyomi": None, "compound_word": None, "compound_reading": None, "compound_meaning_en": None, "category": "misc"},
    {"character": "電", "meaning_en": "electricity", "onyomi": "デン", "kunyomi": None, "compound_word": "電話", "compound_reading": "でんわ", "compound_meaning_en": "telephone", "category": "misc"},
    {"character": "車", "meaning_en": "car / vehicle", "onyomi": "シャ", "kunyomi": "くるま", "compound_word": "電車", "compound_reading": "でんしゃ", "compound_meaning_en": "train", "category": "misc"},
    {"character": "語", "meaning_en": "language", "onyomi": "ゴ", "kunyomi": None, "compound_word": "日本語", "compound_reading": "にほんご", "compound_meaning_en": "Japanese language", "category": "misc"},
    {"character": "好", "meaning_en": "like", "onyomi": "コウ", "kunyomi": "す(き)", "compound_word": "好き", "compound_reading": "すき", "compound_meaning_en": "like", "category": "misc"},
    {"character": "元", "meaning_en": "origin", "onyomi": "ゲン", "kunyomi": "もと", "compound_word": "元気", "compound_reading": "げんき", "compound_meaning_en": "healthy / energetic", "category": "misc"},
]