VOCAB_SEED = [
    # greetings
    {"word": "おはようございます", "reading": None, "meaning_en": "good morning", "category": "greetings"},
    {"word": "こんにちは", "reading": None, "meaning_en": "hello / good afternoon", "category": "greetings"},
    {"word": "こんばんは", "reading": None, "meaning_en": "good evening", "category": "greetings"},
    {"word": "さようなら", "reading": None, "meaning_en": "goodbye", "category": "greetings"},
    {"word": "おやすみなさい", "reading": None, "meaning_en": "good night", "category": "greetings"},
    {"word": "ありがとうございます", "reading": None, "meaning_en": "thank you", "category": "greetings"},
    {"word": "すみません", "reading": None, "meaning_en": "excuse me / sorry", "category": "greetings"},
    {"word": "ごめんなさい", "reading": None, "meaning_en": "I'm sorry", "category": "greetings"},
    {"word": "はい", "reading": None, "meaning_en": "yes", "category": "greetings"},
    {"word": "いいえ", "reading": None, "meaning_en": "no", "category": "greetings"},
    {"word": "お願いします", "reading": "おねがいします", "meaning_en": "please", "category": "greetings"},
    {"word": "どういたしまして", "reading": None, "meaning_en": "you're welcome", "category": "greetings"},
    {"word": "いってきます", "reading": None, "meaning_en": "I'm off (said when leaving)", "category": "greetings"},
    {"word": "いってらっしゃい", "reading": None, "meaning_en": "see you off (said to someone leaving)", "category": "greetings"},
    {"word": "ただいま", "reading": None, "meaning_en": "I'm home", "category": "greetings"},
    {"word": "おかえりなさい", "reading": None, "meaning_en": "welcome back", "category": "greetings"},
    {"word": "いただきます", "reading": None, "meaning_en": "said before eating", "category": "greetings"},
    {"word": "ごちそうさま", "reading": None, "meaning_en": "said after eating", "category": "greetings"},
    {"word": "はじめまして", "reading": None, "meaning_en": "nice to meet you", "category": "greetings"},
    {"word": "よろしくお願いします", "reading": "よろしくおねがいします", "meaning_en": "please treat me well (intro phrase)", "category": "greetings"},

    # time
    {"word": "一", "reading": "いち", "meaning_en": "one", "category": "time"},
    {"word": "二", "reading": "に", "meaning_en": "two", "category": "time"},
    {"word": "三", "reading": "さん", "meaning_en": "three", "category": "time"},
    {"word": "四", "reading": "よん", "meaning_en": "four", "category": "time"},
    {"word": "五", "reading": "ご", "meaning_en": "five", "category": "time"},
    {"word": "六", "reading": "ろく", "meaning_en": "six", "category": "time"},
    {"word": "七", "reading": "なな", "meaning_en": "seven", "category": "time"},
    {"word": "八", "reading": "はち", "meaning_en": "eight", "category": "time"},
    {"word": "九", "reading": "きゅう", "meaning_en": "nine", "category": "time"},
    {"word": "十", "reading": "じゅう", "meaning_en": "ten", "category": "time"},
    {"word": "何時", "reading": "なんじ", "meaning_en": "what time", "category": "time"},
    {"word": "何分", "reading": "なんぷん", "meaning_en": "what minute", "category": "time"},
    {"word": "今日", "reading": "きょう", "meaning_en": "today", "category": "time"},
    {"word": "明日", "reading": "あした", "meaning_en": "tomorrow", "category": "time"},
    {"word": "昨日", "reading": "きのう", "meaning_en": "yesterday", "category": "time"},
    {"word": "今", "reading": "いま", "meaning_en": "now", "category": "time"},
    {"word": "毎日", "reading": "まいにち", "meaning_en": "every day", "category": "time"},
    {"word": "毎週", "reading": "まいしゅう", "meaning_en": "every week", "category": "time"},
    {"word": "毎月", "reading": "まいつき", "meaning_en": "every month", "category": "time"},
    {"word": "毎年", "reading": "まいとし", "meaning_en": "every year", "category": "time"},
    {"word": "午前", "reading": "ごぜん", "meaning_en": "a.m.", "category": "time"},
    {"word": "午後", "reading": "ごご", "meaning_en": "p.m.", "category": "time"},
    {"word": "朝", "reading": "あさ", "meaning_en": "morning", "category": "time"},
    {"word": "昼", "reading": "ひる", "meaning_en": "noon / daytime", "category": "time"},
    {"word": "夜", "reading": "よる", "meaning_en": "night", "category": "time"},
    {"word": "週末", "reading": "しゅうまつ", "meaning_en": "weekend", "category": "time"},
    {"word": "先週", "reading": "せんしゅう", "meaning_en": "last week", "category": "time"},
    {"word": "今週", "reading": "こんしゅう", "meaning_en": "this week", "category": "time"},
    {"word": "来週", "reading": "らいしゅう", "meaning_en": "next week", "category": "time"},
    {"word": "先月", "reading": "せんげつ", "meaning_en": "last month", "category": "time"},
    {"word": "今月", "reading": "こんげつ", "meaning_en": "this month", "category": "time"},
    {"word": "来月", "reading": "らいげつ", "meaning_en": "next month", "category": "time"},
    {"word": "去年", "reading": "きょねん", "meaning_en": "last year", "category": "time"},
    {"word": "今年", "reading": "ことし", "meaning_en": "this year", "category": "time"},
    {"word": "来年", "reading": "らいねん", "meaning_en": "next year", "category": "time"},

    # family
    {"word": "家族", "reading": "かぞく", "meaning_en": "family", "category": "family"},
    {"word": "両親", "reading": "りょうしん", "meaning_en": "parents", "category": "family"},
    {"word": "父", "reading": "ちち", "meaning_en": "father (one's own)", "category": "family"},
    {"word": "お父さん", "reading": "おとうさん", "meaning_en": "father (polite)", "category": "family"},
    {"word": "母", "reading": "はは", "meaning_en": "mother (one's own)", "category": "family"},
    {"word": "お母さん", "reading": "おかあさん", "meaning_en": "mother (polite)", "category": "family"},
    {"word": "兄", "reading": "あに", "meaning_en": "older brother (one's own)", "category": "family"},
    {"word": "お兄さん", "reading": "おにいさん", "meaning_en": "older brother (polite)", "category": "family"},
    {"word": "姉", "reading": "あね", "meaning_en": "older sister (one's own)", "category": "family"},
    {"word": "お姉さん", "reading": "おねえさん", "meaning_en": "older sister (polite)", "category": "family"},
    {"word": "弟", "reading": "おとうと", "meaning_en": "younger brother", "category": "family"},
    {"word": "妹", "reading": "いもうと", "meaning_en": "younger sister", "category": "family"},
    {"word": "子供", "reading": "こども", "meaning_en": "child", "category": "family"},
    {"word": "友達", "reading": "ともだち", "meaning_en": "friend", "category": "family"},
    {"word": "先生", "reading": "せんせい", "meaning_en": "teacher", "category": "family"},
    {"word": "学生", "reading": "がくせい", "meaning_en": "student", "category": "family"},
    {"word": "会社員", "reading": "かいしゃいん", "meaning_en": "company employee", "category": "family"},
    {"word": "医者", "reading": "いしゃ", "meaning_en": "doctor", "category": "family"},
    {"word": "名前", "reading": "なまえ", "meaning_en": "name", "category": "family"},

    # body_health
    {"word": "頭", "reading": "あたま", "meaning_en": "head", "category": "body_health"},
    {"word": "顔", "reading": "かお", "meaning_en": "face", "category": "body_health"},
    {"word": "目", "reading": "め", "meaning_en": "eye", "category": "body_health"},
    {"word": "耳", "reading": "みみ", "meaning_en": "ear", "category": "body_health"},
    {"word": "口", "reading": "くち", "meaning_en": "mouth", "category": "body_health"},
    {"word": "手", "reading": "て", "meaning_en": "hand", "category": "body_health"},
    {"word": "足", "reading": "あし", "meaning_en": "foot / leg", "category": "body_health"},
    {"word": "体", "reading": "からだ", "meaning_en": "body", "category": "body_health"},
    {"word": "元気", "reading": "げんき", "meaning_en": "healthy / energetic", "category": "body_health"},
    {"word": "病気", "reading": "びょうき", "meaning_en": "sickness", "category": "body_health"},
    {"word": "薬", "reading": "くすり", "meaning_en": "medicine", "category": "body_health"},

    # food
    {"word": "ご飯", "reading": "ごはん", "meaning_en": "rice / meal", "category": "food"},
    {"word": "パン", "reading": None, "meaning_en": "bread", "category": "food"},
    {"word": "水", "reading": "みず", "meaning_en": "water", "category": "food"},
    {"word": "お茶", "reading": "おちゃ", "meaning_en": "tea", "category": "food"},
    {"word": "コーヒー", "reading": None, "meaning_en": "coffee", "category": "food"},
    {"word": "肉", "reading": "にく", "meaning_en": "meat", "category": "food"},
    {"word": "魚", "reading": "さかな", "meaning_en": "fish", "category": "food"},
    {"word": "野菜", "reading": "やさい", "meaning_en": "vegetables", "category": "food"},
    {"word": "果物", "reading": "くだもの", "meaning_en": "fruit", "category": "food"},
    {"word": "卵", "reading": "たまご", "meaning_en": "egg", "category": "food"},
    {"word": "朝ご飯", "reading": "あさごはん", "meaning_en": "breakfast", "category": "food"},
    {"word": "昼ご飯", "reading": "ひるごはん", "meaning_en": "lunch", "category": "food"},
    {"word": "晩ご飯", "reading": "ばんごはん", "meaning_en": "dinner", "category": "food"},
    {"word": "食べる", "reading": "たべる", "meaning_en": "to eat", "category": "food"},
    {"word": "飲む", "reading": "のむ", "meaning_en": "to drink", "category": "food"},
    {"word": "おいしい", "reading": None, "meaning_en": "delicious", "category": "food"},
    {"word": "まずい", "reading": None, "meaning_en": "tastes bad", "category": "food"},

    # objects
    {"word": "本", "reading": "ほん", "meaning_en": "book", "category": "objects"},
    {"word": "新聞", "reading": "しんぶん", "meaning_en": "newspaper", "category": "objects"},
    {"word": "雑誌", "reading": "ざっし", "meaning_en": "magazine", "category": "objects"},
    {"word": "鉛筆", "reading": "えんぴつ", "meaning_en": "pencil", "category": "objects"},
    {"word": "ペン", "reading": None, "meaning_en": "pen", "category": "objects"},
    {"word": "紙", "reading": "かみ", "meaning_en": "paper", "category": "objects"},
    {"word": "机", "reading": "つくえ", "meaning_en": "desk", "category": "objects"},
    {"word": "椅子", "reading": "いす", "meaning_en": "chair", "category": "objects"},
    {"word": "時計", "reading": "とけい", "meaning_en": "clock / watch", "category": "objects"},
    {"word": "傘", "reading": "かさ", "meaning_en": "umbrella", "category": "objects"},
    {"word": "かばん", "reading": None, "meaning_en": "bag", "category": "objects"},
    {"word": "財布", "reading": "さいふ", "meaning_en": "wallet", "category": "objects"},
    {"word": "眼鏡", "reading": "めがね", "meaning_en": "glasses", "category": "objects"},
    {"word": "服", "reading": "ふく", "meaning_en": "clothes", "category": "objects"},
    {"word": "靴", "reading": "くつ", "meaning_en": "shoes", "category": "objects"},
    {"word": "テレビ", "reading": None, "meaning_en": "television", "category": "objects"},
    {"word": "電話", "reading": "でんわ", "meaning_en": "telephone", "category": "objects"},
    {"word": "写真", "reading": "しゃしん", "meaning_en": "photo", "category": "objects"},
    {"word": "お金", "reading": "おかね", "meaning_en": "money", "category": "objects"},

    # places
    {"word": "家", "reading": "いえ / うち", "meaning_en": "house / home", "category": "places"},
    {"word": "学校", "reading": "がっこう", "meaning_en": "school", "category": "places"},
    {"word": "病院", "reading": "びょういん", "meaning_en": "hospital", "category": "places"},
    {"word": "駅", "reading": "えき", "meaning_en": "station", "category": "places"},
    {"word": "会社", "reading": "かいしゃ", "meaning_en": "company", "category": "places"},
    {"word": "図書館", "reading": "としょかん", "meaning_en": "library", "category": "places"},
    {"word": "銀行", "reading": "ぎんこう", "meaning_en": "bank", "category": "places"},
    {"word": "郵便局", "reading": "ゆうびんきょく", "meaning_en": "post office", "category": "places"},
    {"word": "店", "reading": "みせ", "meaning_en": "shop", "category": "places"},
    {"word": "レストラン", "reading": None, "meaning_en": "restaurant", "category": "places"},
    {"word": "公園", "reading": "こうえん", "meaning_en": "park", "category": "places"},
    {"word": "部屋", "reading": "へや", "meaning_en": "room", "category": "places"},
    {"word": "トイレ", "reading": None, "meaning_en": "toilet", "category": "places"},
    {"word": "国", "reading": "くに", "meaning_en": "country", "category": "places"},
    {"word": "日本", "reading": "にほん", "meaning_en": "Japan", "category": "places"},

    # school_work
    {"word": "勉強", "reading": "べんきょう", "meaning_en": "study", "category": "school_work"},
    {"word": "宿題", "reading": "しゅくだい", "meaning_en": "homework", "category": "school_work"},
    {"word": "授業", "reading": "じゅぎょう", "meaning_en": "class / lesson", "category": "school_work"},
    {"word": "テスト", "reading": None, "meaning_en": "test", "category": "school_work"},
    {"word": "教室", "reading": "きょうしつ", "meaning_en": "classroom", "category": "school_work"},
    {"word": "仕事", "reading": "しごと", "meaning_en": "job / work", "category": "school_work"},
    {"word": "休み", "reading": "やすみ", "meaning_en": "day off / rest", "category": "school_work"},
    {"word": "会議", "reading": "かいぎ", "meaning_en": "meeting", "category": "school_work"},

    # nature
    {"word": "天気", "reading": "てんき", "meaning_en": "weather", "category": "nature"},
    {"word": "雨", "reading": "あめ", "meaning_en": "rain", "category": "nature"},
    {"word": "雪", "reading": "ゆき", "meaning_en": "snow", "category": "nature"},
    {"word": "風", "reading": "かぜ", "meaning_en": "wind", "category": "nature"},
    {"word": "空", "reading": "そら", "meaning_en": "sky", "category": "nature"},
    {"word": "山", "reading": "やま", "meaning_en": "mountain", "category": "nature"},
    {"word": "川", "reading": "かわ", "meaning_en": "river", "category": "nature"},
    {"word": "海", "reading": "うみ", "meaning_en": "sea", "category": "nature"},
    {"word": "花", "reading": "はな", "meaning_en": "flower", "category": "nature"},
    {"word": "木", "reading": "き", "meaning_en": "tree", "category": "nature"},
    {"word": "春", "reading": "はる", "meaning_en": "spring", "category": "nature"},
    {"word": "夏", "reading": "なつ", "meaning_en": "summer", "category": "nature"},
    {"word": "秋", "reading": "あき", "meaning_en": "autumn", "category": "nature"},
    {"word": "冬", "reading": "ふゆ", "meaning_en": "winter", "category": "nature"},

    # verbs
    {"word": "行く", "reading": "いく", "meaning_en": "to go", "category": "verbs"},
    {"word": "来る", "reading": "くる", "meaning_en": "to come", "category": "verbs"},
    {"word": "帰る", "reading": "かえる", "meaning_en": "to return", "category": "verbs"},
    {"word": "見る", "reading": "みる", "meaning_en": "to see", "category": "verbs"},
    {"word": "聞く", "reading": "きく", "meaning_en": "to hear / listen / ask", "category": "verbs"},
    {"word": "話す", "reading": "はなす", "meaning_en": "to speak", "category": "verbs"},
    {"word": "読む", "reading": "よむ", "meaning_en": "to read", "category": "verbs"},
    {"word": "書く", "reading": "かく", "meaning_en": "to write", "category": "verbs"},
    {"word": "買う", "reading": "かう", "meaning_en": "to buy", "category": "verbs"},
    {"word": "売る", "reading": "うる", "meaning_en": "to sell", "category": "verbs"},
    {"word": "作る", "reading": "つくる", "meaning_en": "to make", "category": "verbs"},
    {"word": "使う", "reading": "つかう", "meaning_en": "to use", "category": "verbs"},
    {"word": "待つ", "reading": "まつ", "meaning_en": "to wait", "category": "verbs"},
    {"word": "会う", "reading": "あう", "meaning_en": "to meet", "category": "verbs"},
    {"word": "立つ", "reading": "たつ", "meaning_en": "to stand", "category": "verbs"},
    {"word": "座る", "reading": "すわる", "meaning_en": "to sit", "category": "verbs"},
    {"word": "起きる", "reading": "おきる", "meaning_en": "to wake up", "category": "verbs"},
    {"word": "寝る", "reading": "ねる", "meaning_en": "to sleep", "category": "verbs"},
    {"word": "休む", "reading": "やすむ", "meaning_en": "to rest", "category": "verbs"},
    {"word": "働く", "reading": "はたらく", "meaning_en": "to work", "category": "verbs"},
    {"word": "分かる", "reading": "わかる", "meaning_en": "to understand", "category": "verbs"},
    {"word": "知る", "reading": "しる", "meaning_en": "to know", "category": "verbs"},
    {"word": "思う", "reading": "おもう", "meaning_en": "to think", "category": "verbs"},
    {"word": "入る", "reading": "はいる", "meaning_en": "to enter", "category": "verbs"},
    {"word": "出る", "reading": "でる", "meaning_en": "to exit", "category": "verbs"},
    {"word": "開ける", "reading": "あける", "meaning_en": "to open", "category": "verbs"},
    {"word": "閉める", "reading": "しめる", "meaning_en": "to close", "category": "verbs"},

    # adjectives
    {"word": "大きい", "reading": "おおきい", "meaning_en": "big", "category": "adjectives"},
    {"word": "小さい", "reading": "ちいさい", "meaning_en": "small", "category": "adjectives"},
    {"word": "新しい", "reading": "あたらしい", "meaning_en": "new", "category": "adjectives"},
    {"word": "古い", "reading": "ふるい", "meaning_en": "old", "category": "adjectives"},
    {"word": "いい", "reading": None, "meaning_en": "good", "category": "adjectives"},
    {"word": "よい", "reading": None, "meaning_en": "good", "category": "adjectives"},
    {"word": "悪い", "reading": "わるい", "meaning_en": "bad", "category": "adjectives"},
    {"word": "高い", "reading": "たかい", "meaning_en": "tall / expensive", "category": "adjectives"},
    {"word": "安い", "reading": "やすい", "meaning_en": "cheap", "category": "adjectives"},
    {"word": "長い", "reading": "ながい", "meaning_en": "long", "category": "adjectives"},
    {"word": "短い", "reading": "みじかい", "meaning_en": "short", "category": "adjectives"},
    {"word": "忙しい", "reading": "いそがしい", "meaning_en": "busy", "category": "adjectives"},
    {"word": "楽しい", "reading": "たのしい", "meaning_en": "fun", "category": "adjectives"},
    {"word": "難しい", "reading": "むずかしい", "meaning_en": "difficult", "category": "adjectives"},
    {"word": "易しい", "reading": "やさしい", "meaning_en": "easy", "category": "adjectives"},
    {"word": "暑い", "reading": "あつい", "meaning_en": "hot (weather)", "category": "adjectives"},
    {"word": "寒い", "reading": "さむい", "meaning_en": "cold (weather)", "category": "adjectives"},
    {"word": "暖かい", "reading": "あたたかい", "meaning_en": "warm", "category": "adjectives"},
    {"word": "涼しい", "reading": "すずしい", "meaning_en": "cool", "category": "adjectives"},
    {"word": "きれい", "reading": None, "meaning_en": "pretty / clean", "category": "adjectives"},
    {"word": "静か", "reading": "しずか", "meaning_en": "quiet", "category": "adjectives"},
    {"word": "有名", "reading": "ゆうめい", "meaning_en": "famous", "category": "adjectives"},
    {"word": "便利", "reading": "べんり", "meaning_en": "convenient", "category": "adjectives"},
    {"word": "上手", "reading": "じょうず", "meaning_en": "skillful", "category": "adjectives"},
    {"word": "下手", "reading": "へた", "meaning_en": "unskillful", "category": "adjectives"},
    {"word": "好き", "reading": "すき", "meaning_en": "like", "category": "adjectives"},
    {"word": "嫌い", "reading": "きらい", "meaning_en": "dislike", "category": "adjectives"},

    # question_words
    {"word": "何", "reading": "なに / なん", "meaning_en": "what", "category": "question_words"},
    {"word": "誰", "reading": "だれ", "meaning_en": "who", "category": "question_words"},
    {"word": "どこ", "reading": None, "meaning_en": "where", "category": "question_words"},
    {"word": "いつ", "reading": None, "meaning_en": "when", "category": "question_words"},
    {"word": "どう", "reading": None, "meaning_en": "how", "category": "question_words"},
    {"word": "どうやって", "reading": None, "meaning_en": "how (in what way)", "category": "question_words"},
    {"word": "どうして", "reading": None, "meaning_en": "why", "category": "question_words"},
    {"word": "なぜ", "reading": None, "meaning_en": "why", "category": "question_words"},
    {"word": "いくら", "reading": None, "meaning_en": "how much (price)", "category": "question_words"},
    {"word": "いくつ", "reading": None, "meaning_en": "how many", "category": "question_words"},

    # adverbs
    {"word": "とても", "reading": None, "meaning_en": "very", "category": "adverbs"},
    {"word": "少し", "reading": "すこし", "meaning_en": "a little", "category": "adverbs"},
    {"word": "たくさん", "reading": None, "meaning_en": "a lot", "category": "adverbs"},
    {"word": "また", "reading": None, "meaning_en": "again", "category": "adverbs"},
    {"word": "まだ", "reading": None, "meaning_en": "still / not yet", "category": "adverbs"},
    {"word": "もう", "reading": None, "meaning_en": "already", "category": "adverbs"},
    {"word": "すぐに", "reading": None, "meaning_en": "right away", "category": "adverbs"},
    {"word": "ゆっくり", "reading": None, "meaning_en": "slowly", "category": "adverbs"},
    {"word": "いつも", "reading": None, "meaning_en": "always", "category": "adverbs"},
    {"word": "時々", "reading": "ときどき", "meaning_en": "sometimes", "category": "adverbs"},
    {"word": "全然", "reading": "ぜんぜん", "meaning_en": "not at all (+ negative)", "category": "adverbs"},
    {"word": "そして", "reading": None, "meaning_en": "and then", "category": "adverbs"},
    {"word": "でも", "reading": None, "meaning_en": "but", "category": "adverbs"},
    {"word": "しかし", "reading": None, "meaning_en": "but", "category": "adverbs"},
    {"word": "だから", "reading": None, "meaning_en": "so / therefore", "category": "adverbs"},
]