export const FEATURE_FLAGS = {
  FEATURE_FOUNDATION_SHELL: import.meta.env.VITE_FEATURE_FOUNDATION_SHELL === "true",
  FEATURE_CONTENT_MANAGEMENT: false,
  FEATURE_STUDY_FLASHCARDS: import.meta.env.VITE_FEATURE_STUDY_FLASHCARDS === "true",
  FEATURE_QUIZ_MODE: import.meta.env.VITE_FEATURE_QUIZ_MODE === "true",
  FEATURE_SENTENCE_GENERATOR: import.meta.env.VITE_FEATURE_SENTENCE_GENERATOR === "true",
};