export const FEATURE_FLAGS = {
  FEATURE_FOUNDATION_SHELL: import.meta.env.VITE_FEATURE_FOUNDATION_SHELL === "true",
  FEATURE_CONTENT_MANAGEMENT: false,
  FEATURE_STUDY_FLASHCARDS: import.meta.env.VITE_FEATURE_STUDY_FLASHCARDS === "true",
};