"""add items and sentences tables

Revision ID: 07026ad7a640
Revises: caf69c4b502d
Create Date: 2026-08-05 13:19:41.132127

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '07026ad7a640'
down_revision: str | Sequence[str] | None = 'caf69c4b502d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence_folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_sentences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jp_text', sa.Text(), nullable=False),
    sa.Column('reading', sa.Text(), nullable=False),
    sa.Column('meaning_en', sa.Text(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('source_item_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['sentence_folders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_sentences_folder_id'), 'generated_sentences', ['folder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_sentences_folder_id'), table_name='generated_sentences')
    op.drop_table('generated_sentences')
    op.drop_table('sentence_folders')
    # ### end Alembic commands ###