"""add leaderboard devices and runs tables

Revision ID: 24d59c83439d
Revises: c8a4e91d7b52
Create Date: 2026-08-21 07:27:23.748090

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '24d59c83439d'
down_revision: str | Sequence[str] | None = 'c8a4e91d7b52'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaderboard_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('quiz_type', sa.Enum('CHOICE', 'PAIRS', name='leaderboard_quiz_type'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['leaderboard_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_runs_device_id'), 'leaderboard_runs', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_runs_device_id'), table_name='leaderboard_runs')
    op.drop_table('leaderboard_runs')
    op.drop_table('leaderboard_devices')
    # ### end Alembic commands ###

    # Autogenerate does not emit this: sa.Enum's CREATE TYPE on upgrade()
    # has no matching DROP TYPE here, so a downgrade followed by another
    # upgrade fails with "type already exists" — reproduced and fixed
    # while building this migration. Dropped last, after the table that
    # references it, matching caf69c4b502d's content_status/content_source
    # precedent for the same reason: dropping the type first would fail
    # while a column still references it.
    postgresql.ENUM(name='leaderboard_quiz_type').drop(op.get_bind())