"""add pattern_romaji and example_romaji to grammar entries

Revision ID: b3f1c27a9e40
Revises: 07026ad7a640
Create Date: 2026-08-11 09:12:04.881233

Kanji and vocab romaji are computed at read time in `*EntryRead`
(`services/romaji.to_romaji`) rather than stored — see ADR 015. Both are
single words with no bare kanji and no word-boundary ambiguity, so a
column would only be a cache.

Grammar's two romaji fields don't have that property. `pattern` has no
separate reading to derive from, mixes in bare kanji, and needs word
segmentation a character-level pass can't do. `example_reading` (a full
sentence, unlike a single kanji or vocab reading) has the same
segmentation problem even though it's plain kana — measured against the
seed set, mechanical transliteration disagrees with the correct romaji for
25 of the 26 seeded examples, purely on missing word spacing. Both are
therefore authored content, stored rather than derived.

Hand-written rather than autogenerated — two nullable column additions
don't need a live database to produce the file.
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b3f1c27a9e40'
down_revision: str | Sequence[str] | None = '07026ad7a640'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('grammar_entries', sa.Column('pattern_romaji', sa.Text(), nullable=True))
    op.add_column('grammar_entries', sa.Column('example_romaji', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('grammar_entries', 'example_romaji')
    op.drop_column('grammar_entries', 'pattern_romaji')
