"""add romaji to generated sentences

Revision ID: c8a4e91d7b52
Revises: b3f1c27a9e40
Create Date: 2026-08-11 11:41:18.204517

Nullable with no backfill. Sentences saved before epic 009 have no romaji
and cannot get one retroactively — it comes from the generation provider
at creation time, and a sentence can't be transliterated from its reading
after the fact because that needs word segmentation (ADR 015).

Hand-written rather than autogenerated — one nullable column addition
doesn't need a live database to produce the file.
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c8a4e91d7b52'
down_revision: str | Sequence[str] | None = 'b3f1c27a9e40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('generated_sentences', sa.Column('romaji', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('generated_sentences', 'romaji')
