"""add usage counters table

Revision ID: e106fe5d665b
Revises: 24d59c83439d
Create Date: 2026-08-22 20:50:39.443935

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e106fe5d665b'
down_revision: str | Sequence[str] | None = '24d59c83439d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_counters',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'window_start')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_counters')
    # ### end Alembic commands ###